apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-newrelic-license
type: Opaque
data:
  newrelic-license: ENC[AES256_GCM,data:AgBEBaAyBoOyGLMZ+/gL4vjx840E0jWCn+XkKNDpvUskZTswbauvZvUblCa3L9VwkMGSOf6N7Rg=,iv:bzBcdArB2fQaNJ7cRgqBlDReOOmpvbciZhZem99sWRM=,tag:UkDnhOZnmYSF/Hz1Pb1WNg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGLy9YVHQ0STJiVEw0WXRC
        akQ3ampETzJtUFFHRjJXc0ZCN2tCeXFSNGhnCm1OY3FHblFReHg4cG5IZzRyNHRW
        dWxZVU96aGFrOCtTcVFqWEJsblE4SkEKLS0tIDhoU2JsL1lROS84eUREZVM3RS9G
        UkszMzUxZkFKbDd6NW1qc0lXWGdwZUEK9ROv/xsDnapulFV3CzKAPLTZzNPEWjlX
        XBg+HtGKygGJgf9ODnd4cUHvnOpdJZ+Wr+c3+Ti0OmyeVFagp7TCCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-01-21T12:29:12Z"
  mac: ENC[AES256_GCM,data:uJcL2WPKRKvUY9hNnwa01nd8spPSM8Q4pD9M22l8BCVcM3wPt7zsMuFRih6OOhGGXWEEnxKO8KKkYmqXReiqvFlpKFFX/hueyHlHmiE2DHIUBmGu3fKiaLH85ABtHrGea//e1fZi0+V3x//KcO34tJVdAjnK2kK82bau0vz8GNM=,iv:K9NWv0BvmDw6mzTLZ0Y0FxslfIfH20CsTfEIZt/HY3Y=,tag:yWH9qfUoXkhHohO+icf6Tg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
