# environment
env: prod
# container image
image:
  organization: morningnightguild
  tag: 2023-05-04-13-21-59
  migrate:
    repository: platform-db-migrate
  backup:
    repository: platform-db-backup
