# environment
env: prod
# container image
image:
  organization: morningnightguild
  tag: 2023-07-29-13-12-50
  migrate:
    repository: platform-db-migrate
  backup:
    repository: platform-db-backup
