apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-api-key
type: Opaque
data:
  api-key: ENC[AES256_GCM,data:0St+HwjGv3ngFybl1iIluVx1vllRy5r0AjgKKsP/j++4syvI5p7Cog==,iv:dwulc7Gcg2gK37t9O1s3EYosEkzLIZgS9IbqEGcIDUA=,tag:Q6UZowfOgmBDwZzXVkUXLQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIR2htRXRWdWc0NDR6Z2Rs
        U1J4ZDhhVEpGUVlZSU5uM0swOEdnd29xZ21BCnEyRUgrb295dUJXMHVFSHhuL002
        TGdnOHJnakxEMzBma240NGVmQy9yK1kKLS0tIEZvU0p2TVJlek1yT2ErR0hnd290
        d1ZaYVRabnE0dnJ3OHBITUdpUTJ5dGcKHrsZy5G8ujmYiOcTg2qEUOvgLJaGvXNF
        Vq+h5N/fyfLY70DeM56Pu7k9PZ7MrP2uP+YF9vvlZUZzboG09t36yw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-01-21T12:27:15Z"
  mac: ENC[AES256_GCM,data:oTbUu/1jDMnz6oUH04Y8nUigsiNuXIPVVLxld+dzBsFl2HSDO/1afA4JriZS37VveeqK3DlR8Wdjge0g78DhCbi54dKLwNSU+cu6xsEXc2nMTZD7PDOmim2MruB9+ToPqitY1iahvbLWdodWNyaOTA8WpsEHXUta8N+6yS/421M=,iv:4LETq6pE2SIh7d06xvO3rzPm1Iw9wUEtmUoXM0XNn1s=,tag:pL092dx3e9vqj9ArR55fPg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
