# environment
env: prod
# container image
image:
  organization: morningnightguild
  repository: platform-app-api
  tag: 2023-03-15-15-09-00
# cors
cors_allow_origins: https://morning-night-guild-platform-web.vercel.app
