# environment
env: prod
# container image
image:
  organization: morningnightguild
  repository: platform-app-api
  tag: 2023-07-29-13-12-50
# cors
cors_allow_origins: https://morning-night-guild-platform-web.vercel.app
