apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
  labels:
    app: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform
  template:
    metadata:
      labels:
        app: platform
    spec:
      containers:
        - name: platform
          image: "{{ .Values.image.organization }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: ENV
              value: "{{ .Values.env }}"
            - name: PORT
              value: "8080"
            - name: CORS
              value: "https://platform-lovat.vercel.app"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: platform-secret-database-url
                  key: database-url
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secret-api-key
                  key: api-key
            - name: NEWRELIC_APP_NAME
              valueFrom:
                secretKeyRef:
                  name: platform-secret-newrelic-app-name
                  key: newrelic-app-name
            - name: NEWRELIC_LICENSE
              valueFrom:
                secretKeyRef:
                  name: platform-secret-newrelic-license
                  key: newrelic-license
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
