apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-newrelic-app-name
type: Opaque
data:
  newrelic-app-name: ENC[AES256_GCM,data:6EeN+q7NbdPlq/y43Cw7uVrQ/v56GachgF9z16AgUJi+rT8Zwk67bw==,iv:LwWgo2VDyz7Our8TfuSmhEQ4jbbcsF2OeAKwK4R7jAk=,tag:bH0y8Wi1Vr5+8bP6jrCRCg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTDAxNnJSQW11T2drMllm
        dy9NNmV1b0V0N1VuZW9CTzlpckJseUtLemtRCk5vaTF5cm8wcXdzUmcxOVU3cVJa
        REQyQ0lRNWdYYkoyMXZwUGhsL1FXRDgKLS0tIEF4OFZMWkwzQVczbi9HYmFZVFJk
        WU1FY21FUVFPR0w3cWZVWXlmbDNHdU0K4PhYeoOm9X8gDFIpPRbA/8ZewwV7FpYF
        Cr5iqI4HxZx6ZUiXFpObx591oldnhSnPT+Olk8WwFiigYjDgyo2e2A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-01-21T12:29:07Z"
  mac: ENC[AES256_GCM,data:XsUZ26o51fHywzL+OslgeBvWkdxly7wdowqMV3JYjXc6YskBDWS+s5woNvTBoYceRdkajWg9GjuSWk46QAGZtEQXhUVtsWc8QCJxhzvUBmSCxFRXeNTl8+BYQniXksReJThNpXFkWGqv/BGk+qoOsL2tXKrxkQsn677vFZXjOBM=,iv:ws7/ejTNXdlILDEEFtBVoMvJpl2J6MgrM9mDtSvNSQ0=,tag:EkDK453L5TWcnds5oZCXww==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
