apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-api-key
type: Opaque
data:
  api-key: ENC[AES256_GCM,data:y+9ng473AN8Ha7YDFx0fkwoq/ARPRR4Dii49lCgnduXdWc4LsWYPqw==,iv:sbaD5XXsqSnD+pWpHBMrTlCF/zw7a6EHCT6axY4gnpU=,tag:MNVwPFsdTxr60tEyWSzw8w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eEJSREFaWFlHOGpTdENw
        cUxFL0NBUEE5b0drMGxVTlhoSm5JWWVvVlR3CnJkTnRpZFRDRnBQNEdWMVBHdWFU
        VzBXcDNMQ3J4cHZ3MXYwL3JwK0NEYWcKLS0tIGNlSmhsL2k5QkE0MGw0c2hCTFJW
        RUt5NHZSb21ldmNGTjh0d2RFbHVEdkEKdaxMFucuZ+n9eDICETDCa0SAv5DyH1cS
        nbtElBvY4JeeUS9oSS85Apq2GSBMrZ03hx/9OSOwL+PYGqhFC4PrlQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-03-13T14:45:05Z"
  mac: ENC[AES256_GCM,data:ybJJ49x0jVbJXwEEuheufYgxHCUEbFA5t/Kj7iCbuYEhateFKEpArbGpvyAig1j6aCJ3OKmlFncUfw5MjARdkRng6hg9NgHcpet2V3NhwPxoz+jCOpabEiCjL+BbeMNTPbKMWS+9t/UUH6rHQF8osTS5ksO6mZmFxtIwJBX6aXU=,iv:3EtdC5N0PqwkTuFzuicYKCFgzThd90hTSi6T5iKExys=,tag:6QGDlwiuJdzKeNSjAuTO/g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
