apiVersion: v1
kind: Secret
metadata:
  name: platform-secret-jwt-secret
type: Opaque
data:
  jwt-secret: ENC[AES256_GCM,data:yXngYJryO8bObWzlWSNOIL25BrRUX5INkwnXk7K27t5tPylOtySPjYZzeJvfKSllOm/SONhW7OJqeuhUMGbXGZ05xys3k11rtXeh5VEGtiX523ldlu29CQ==,iv:GUGZsKd9GBSnTzECzi8OLq6R2UUQWt0JgWWibSpf22E=,tag:0GLYTpqW5LOfTaOMq/oLSA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1jglwyzrn80auhq0k93mv8zqn5ezt6ngsdvhjn23nwfh0quq7wussn2tdm3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnem1CNm5HSjhpek4yQWRm
        NzY1RU1acVZRdGUvNE5tSjlQRW9YS2xxVmhJCnQxU3lzREhUZUtTUldYcjEwUXFP
        aTVQTkZYb2dETVowZU9uWkp0bFYwVm8KLS0tIFZQQUhRTlp4Mjk0SkMzTlAxNXVE
        eWUwV0pVNHdCbUtHMGtPMkQ0cFRWbnMK+1mBTzcjsvVJboLTNFJHq8mWBqsbqA5I
        cfyTgUuwiTrmo2lqo0D21AWlt8fkXmzA8NiuLuDjUUyXeWE5XYN8bg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-04-02T05:56:31Z"
  mac: ENC[AES256_GCM,data:iT1RqA9YsC8+UfrPd8FhNl1gdmVHLvLJxebSjzJn5Ud8graT2i3EJW/YGRi5jLNN1z+khBNg/Pf+Ewzruz8Jb+cZjJVFU2/BYp9zqiR3zyJQlmvHJod8B2tKNDjzapUZ5rDMaGH0mTK9J3Y4qto+WaNUpd2TikCy5O2Z57nn3+g=,iv:21wsVgZH2tv33mjlGXMGiP3+OlELqQrpmwEX9CkGVgg=,tag:OqNQH0HtE5dmrkyIln9h6A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$$
  version: 3.7.3
