apiVersion: batch/v1
kind: CronJob
metadata:
  name: platform-db-backup
spec:
  schedule: "0 18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: platform-db-backup
              image: "{{ .Values.image.organization }}/{{ .Values.image.backup.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: IfNotPresent
              env:
                - name: PRIMARY_DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: platform-secret-cockroach-db-url
                      key: cockroach-db-url
                - name: SECONDARY_DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: platform-secret-yugabyte-db-url
                      key: yugabyte-db-url
          restartPolicy: Never
