apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-app-api
  labels:
    app: platform-app-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform-app-api
  template:
    metadata:
      labels:
        app: platform-app-api
    spec:
      initContainers:
        - name: platform-app-core-health
          image: busybox:1.36.0-uclibc
          command: ['sh', '-c', "until nc platform-app-core 8080; do echo waiting for platform-app-core; sleep 2; done; echo healthy platform-app-core"]
      containers:
        - name: platform-app-api
          image: "{{ .Values.image.organization }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: ENV
              value: "{{ .Values.env }}"
            - name: PORT
              value: "8080"
            - name: APP_CORE_URL
              value: "http://platform-app-core:8080"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secret-api-key
                  key: api-key
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform-secret-jwt-secret
                  key: jwt-secret
            - name: CORS_ALLOW_ORIGINS
              value: "{{ .Values.cors_allow_origins }}"
            - name: NEWRELIC_APP_NAME
              value: ""
            - name: NEWRELIC_LICENSE
              value: ""
            - name: COOKIE_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: platform-secret-app-api-domain
                  key: app-api-domain
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: platform-secret-upstash-redis-url
                  key: upstash-redis-url
            - name: FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secret-firebase-api-key
                  key: firebase-api-key
            - name: FIREBASE_SECRET
              valueFrom:
                secretKeyRef:
                  name: platform-secret-firebase-secret
                  key: firebase-secret
            - name: FIREBASE_API_ENDPOINT
              value: https://identitytoolkit.googleapis.com
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secret-resend-api-key
                  key: resend-api-key
            - name: RESEND_SENDER
              value: noreply@resend.dev
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: 128Mi
