name: container check
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    paths:
      - .github/workflows/container.check.yaml
      - charts/**/*.yaml
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v1.33.0
      - name: Install yq
        run: ${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua install -t yq
      - name: Docker pull
        run: |
          for chart in $(find charts -mindepth 1 -maxdepth 1 -type d) ; do
            if [[ "${chart}" == "charts/secret" ]] ; then
              continue
            fi
            echo "${chart}"
            organization=$(yq '.image.organization' ${chart}/values.yaml)
            repository=$(yq '.image.repository' ${chart}/values.yaml)
            tag=$(yq '.image.tag' ${chart}/values.yaml)
            docker pull ${organization}/${repository}:${tag}
          done
