name: container check
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    paths:
      - .github/workflows/container.check.yaml
      - charts/**/*.yaml
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v1.33.0
      - name: Install yq
        run: ${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua install -t yq
      - name: Docker pull app api
        run: |
          organization=$(yq '.image.organization' charts/app-api/values.yaml)
          repository=$(yq '.image.repository' charts/app-api/values.yaml)
          tag=$(yq '.image.tag' charts/app-api/values.yaml)
          docker pull ${organization}/${repository}:${tag}
      - name: Docker pull app core
        run: |
          organization=$(yq '.image.organization' charts/app-core/values.yaml)
          repository=$(yq '.image.repository' charts/app-core/values.yaml)
          tag=$(yq '.image.tag' charts/app-core/values.yaml)
          docker pull ${organization}/${repository}:${tag}
      - name: Docker database pull
        run: |
          organization=$(yq '.image.organization' charts/database/values.yaml)
          tag=$(yq '.image.tag' charts/database/values.yaml)
          migrate=$(yq '.image.migrate.repository' charts/database/values.yaml)
          docker pull ${organization}/${migrate}:${tag}
          backup=$(yq '.image.backup.repository' charts/database/values.yaml)
          docker pull ${organization}/${backup}:${tag}
